package kasir;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author MyBook Hype AMD
 */
public class PanelKasir extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuBarang
     */
    public PanelKasir() {
        initComponents();
        loadBarangKePanelList();
        panelKeranjang.setLayout(new BoxLayout(panelKeranjang, BoxLayout.Y_AXIS));
        panelKeranjang.setAlignmentY(Component.TOP_ALIGNMENT);
        JPanel wrapper = new JPanel(new BorderLayout());
        wrapper.add(panelKeranjang, BorderLayout.NORTH);
        jScrollPane1.setViewportView(wrapper);
       
        panelList.setLayout(new WrapLayout(FlowLayout.LEFT, 10, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelList = new javax.swing.JPanel();
        tCari = new javax.swing.JTextField();
        bKosongkan = new javax.swing.JButton();
        bBayar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelKeranjang = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(939, 657));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 46));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Kasir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportView(panelList);

        panelList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        panelList.setMaximumSize(new java.awt.Dimension(1000, 32767));
        jScrollPane2.setViewportView(panelList);

        tCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tCari.setText("Masukkan nama item...");
        tCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tCariMouseClicked(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });

        bKosongkan.setBackground(new java.awt.Color(0, 204, 51));
        bKosongkan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bKosongkan.setForeground(new java.awt.Color(255, 255, 255));
        bKosongkan.setText("Kosongkan");
        bKosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKosongkanActionPerformed(evt);
            }
        });

        bBayar.setBackground(new java.awt.Color(0, 204, 51));
        bBayar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bBayar.setForeground(new java.awt.Color(255, 255, 255));
        bBayar.setText("BAYAR");
        bBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBayarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Sub Total");

        labelSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSubtotal.setText("Rp. 57.000");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelKeranjang.setBackground(new java.awt.Color(255, 255, 255));
        panelKeranjang.setLayout(new javax.swing.BoxLayout(panelKeranjang, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(panelKeranjang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bKosongkan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSubtotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bBayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bKosongkan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bBayar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private JPanel createBarangPanel(String nama, String harga, String fotoPath) {
    JPanel barangPanel = new JPanel(new BorderLayout());
    barangPanel.setPreferredSize(new Dimension(140, 170));
    barangPanel.setBackground(Color.WHITE);
    barangPanel.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

    // ======== Gambar Barang ========
    JLabel lblGambar = new JLabel("", SwingConstants.CENTER);
    lblGambar.setPreferredSize(new Dimension(140, 170));
    if (fotoPath != null && !fotoPath.isEmpty()) {
        ImageIcon img = new ImageIcon(fotoPath);
        Image scaled = img.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH);
        lblGambar.setIcon(new ImageIcon(scaled));
    } else {
        lblGambar.setText("No Image");
        lblGambar.setForeground(Color.GRAY);
    }

    // ======== Nama Barang ========
    JLabel lblNama = new JLabel(nama, SwingConstants.CENTER);
    lblNama.setFont(new Font("Segoe UI", Font.BOLD, 14));
    lblNama.setForeground(Color.BLACK);

    // ======== Harga dengan badge biru ========
    JLabel lblHarga = new JLabel("Rp. " + harga, SwingConstants.CENTER);
    lblHarga.setOpaque(true);
    lblHarga.setBackground(new Color(0, 123, 255)); // biru
    lblHarga.setForeground(Color.WHITE);
    lblHarga.setFont(new Font("Segoe UI", Font.BOLD, 12));
    lblHarga.setBorder(BorderFactory.createEmptyBorder(3, 8, 3, 8));
    
    
    // ======== Panel bawah (nama + harga) ========
    JPanel bottomPanel = new JPanel(new GridLayout(2, 1));
    bottomPanel.setBackground(Color.WHITE);
    bottomPanel.add(lblNama);
    bottomPanel.add(lblHarga);
    
    // ======== Tambah ke panel utama ========
    barangPanel.add(lblGambar, BorderLayout.CENTER);
    barangPanel.add(bottomPanel, BorderLayout.SOUTH);
    
    barangPanel.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
 
        panelKeranjang.add(createItemKeranjangPanel(nama, harga), 0);

        panelKeranjang.revalidate();
        panelKeranjang.repaint();
        recalculateSubtotal();
    }
});
    return barangPanel;
}

private JPanel createItemKeranjangPanel(String nama, String hargaSatuan) {
    int hargaInt = Integer.parseInt(hargaSatuan);

    JPanel itemPanel = new JPanel(new GridBagLayout());
    itemPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
    itemPanel.setBackground(Color.WHITE);
    itemPanel.setBackground(new Color(245, 247, 250)); // abu soft
    itemPanel.setBorder(BorderFactory.createCompoundBorder(
    BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(220, 220, 220)),
    BorderFactory.createEmptyBorder(8, 8, 8, 8)
));
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(5, 10, 5, 10);
    gbc.gridy = 0; // semua 1 baris

    // ====== Nama Barang (kiri)
    JLabel lblNama = new JLabel(nama);
    lblNama.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    gbc.gridx = 0;
    gbc.weightx = 1.0; 
    gbc.anchor = GridBagConstraints.WEST;
    itemPanel.add(lblNama, gbc);

    // ====== Panel qty tengah
    JPanel qtyPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0));
    qtyPanel.setBackground(Color.WHITE);

    JButton btnMinus = new JButton("-");
    JLabel lblQty = new JLabel("1", SwingConstants.CENTER);
    JButton btnPlus = new JButton("+");
    Dimension btnSize = new Dimension(35, 25);
    
    btnPlus.setPreferredSize(btnSize);
    btnPlus.setBackground(new Color(0, 150, 136));  // hijau teal
    btnPlus.setForeground(Color.WHITE);
    btnPlus.setFocusPainted(false);
    btnPlus.setFont(new Font("Segoe UI", Font.BOLD, 18));
   
    btnMinus.setPreferredSize(btnSize);
    btnMinus.setBackground(new Color(244, 67, 54)); // merah soft
    btnMinus.setForeground(Color.WHITE);
    btnMinus.setFocusPainted(false);
    btnMinus.setFont(new Font("Segoe UI", Font.BOLD, 18));
    
    btnPlus.putClientProperty("JButton.buttonType", "roundRect");
    btnMinus.putClientProperty("JButton.buttonType", "roundRect");
    
    qtyPanel.add(btnMinus);
    qtyPanel.add(lblQty);
    qtyPanel.add(btnPlus);

    gbc.gridx = 1;
    gbc.weightx = 0;
    gbc.anchor = GridBagConstraints.CENTER;
    itemPanel.add(qtyPanel, gbc);


    JPanel rightPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 5, 0));
    rightPanel.setBackground(Color.WHITE);
    rightPanel.setOpaque(false);
    rightPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
    JLabel lblTotalHarga = new JLabel("Rp " + hargaSatuan);
    lblTotalHarga.setFont(new Font("Segoe UI", Font.BOLD, 14));
    lblTotalHarga.setPreferredSize(new Dimension(80, 25));
    lblTotalHarga.setForeground(new Color(0, 123, 255)); // biru terang
    lblTotalHarga.setFont(new Font("Segoe UI", Font.BOLD, 14));
    lblTotalHarga.setOpaque(false);
    
    JButton btnDelete = new JButton("×");
    btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 18));
    btnDelete.setPreferredSize(new Dimension(40, 30)); 
    btnDelete.setFocusPainted(false);
    btnDelete.setBorder(null);
    btnDelete.setBackground(Color.WHITE);
    btnDelete.setForeground(Color.RED);
    btnDelete.setContentAreaFilled(false);
    btnDelete.setBorderPainted(false);
    rightPanel.add(lblTotalHarga);
    rightPanel.add(btnDelete);

    gbc.gridx = 2;
    gbc.anchor = GridBagConstraints.EAST;
    itemPanel.add(rightPanel, gbc);

    // ====== LOGIC qty
    final int[] qty = {1};
    btnPlus.addActionListener(e -> {
        qty[0]++;
        lblQty.setText(String.valueOf(qty[0]));
        lblTotalHarga.setText("Rp " + (hargaInt * qty[0]));
        recalculateSubtotal();
    });

    btnMinus.addActionListener(e -> {
        if (qty[0] > 1) {
            qty[0]--;
            lblQty.setText(String.valueOf(qty[0]));
            lblTotalHarga.setText("Rp " + (hargaInt * qty[0]));
            recalculateSubtotal();
        }
    });

    // Tombol hapus
    btnDelete.addActionListener(e -> {
        panelKeranjang.remove(itemPanel);
        panelKeranjang.revalidate();
        panelKeranjang.repaint();
        recalculateSubtotal();
    });

    return itemPanel;
}

private int recalculateSubtotal() {
    int subtotal = 0;

    for (Component c : panelKeranjang.getComponents()) {
        if (c instanceof JPanel) {
            JPanel itemPanel = (JPanel) c;

            // Cari label harga total di itemPanel
            for (Component comp : itemPanel.getComponents()) {
                if (comp instanceof JPanel) {
                    JPanel innerPanel = (JPanel) comp;
                    for (Component innerComp : innerPanel.getComponents()) {
                        if (innerComp instanceof JLabel) {
                            JLabel lbl = (JLabel) innerComp;
                            String text = lbl.getText();

                            if (text.startsWith("Rp")) {
                                // Ambil angka setelah "Rp "
                                String num = text.replace("Rp", "").replace(".", "").trim();
                                try {
                                    subtotal += Integer.parseInt(num);
                                } catch (NumberFormatException e) {
                                    // abaikan
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    labelSubtotal.setText("Rp " + subtotal);
    return subtotal;
}


public void loadBarangKePanelList() {
    panelList.removeAll();

    try (Connection con = koneksi.konek()) {
        String sql = "SELECT nama_barang, harga, foto FROM barang where stok > 0";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            String nama = rs.getString("nama_barang");
            String harga = rs.getString("harga");
            String foto = rs.getString("foto");

            JPanel barangPanel = createBarangPanel(nama, harga, foto);
            panelList.add(barangPanel);

        }

        panelList.revalidate();
        panelList.repaint();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void tCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCariMouseClicked
        // TODO add your handling code here:
        tCari.setText("");
    }//GEN-LAST:event_tCariMouseClicked

    private void bBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBayarActionPerformed
        // TODO add your handling code here:
        int totalKeranjang = recalculateSubtotal();
        kasirPopup dialog = new kasirPopup((Frame) SwingUtilities.getWindowAncestor(this), true, panelKeranjang);
        dialog.setTotalHarga(totalKeranjang);
        dialog.setVisible(true);
    }//GEN-LAST:event_bBayarActionPerformed

    private void bKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKosongkanActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin mengosongkan keranjang?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        panelKeranjang.removeAll();       // hapus semua item di keranjang
        panelKeranjang.revalidate();      // refresh layout
        panelKeranjang.repaint();         // gambar ulang panel

        recalculateSubtotal();            // update subtotal jadi Rp 0
    }         
    }//GEN-LAST:event_bKosongkanActionPerformed

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        // TODO add your handling code here:
        String keyword = tCari.getText();
        filterBarang(keyword);
    }//GEN-LAST:event_tCariKeyReleased
private void filterBarang(String keyword) {
    keyword = keyword.toLowerCase().trim(); // biar gak case sensitive

    for (Component comp : panelList.getComponents()) {
        if (comp instanceof JPanel barangPanel) {

            String namaBarang = "";

            // Cari label nama barang dari bottomPanel
            for (Component subComp : barangPanel.getComponents()) {
                if (subComp instanceof JPanel bottomPanel) {
                    for (Component labelComp : bottomPanel.getComponents()) {
                        if (labelComp instanceof JLabel lblNama) {
                            namaBarang = lblNama.getText().toLowerCase();
                            break;
                        }
                    }
                }
            }

            // cocok atau tidak?
            boolean match = namaBarang.contains(keyword);

            // tampilkan atau sembunyikan
            barangPanel.setVisible(match);
        }
    }

    // Refresh tampilan
    panelList.revalidate();
    panelList.repaint();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBayar;
    private javax.swing.JButton bKosongkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JPanel panelKeranjang;
    private javax.swing.JPanel panelList;
    private javax.swing.JTextField tCari;
    // End of variables declaration//GEN-END:variables
}
