/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MyBook Hype AMD
 */
public class tes extends javax.swing.JFrame {

    /**
     * Creates new form tes
     */
    public tes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dinarmart = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        bDashboard = new javax.swing.JButton();
        bKasir = new javax.swing.JButton();
        bPenjualan = new javax.swing.JButton();
        bBarang = new javax.swing.JButton();
        bPengaturan = new javax.swing.JButton();
        bUser = new javax.swing.JButton();
        bTentang = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(986, 657));

        content.setPreferredSize(new java.awt.Dimension(730, 657));
        content.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(55, 61, 79));

        dinarmart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dinarmart.setForeground(new java.awt.Color(255, 255, 255));
        dinarmart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-store-50.png"))); // NOI18N
        dinarmart.setText("Dinar Mart");

        sidebar.setBackground(new java.awt.Color(51, 51, 51));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 657));

        bDashboard.setBackground(new java.awt.Color(51, 51, 51));
        bDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-dashboard-30.png"))); // NOI18N
        bDashboard.setText("Dashboard");
        bDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDashboard.setIconTextGap(20);
        bDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDashboardActionPerformed(evt);
            }
        });

        bKasir.setBackground(new java.awt.Color(51, 51, 51));
        bKasir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bKasir.setForeground(new java.awt.Color(255, 255, 255));
        bKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-cashier-30.png"))); // NOI18N
        bKasir.setText("Kasir");
        bKasir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bKasir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKasir.setIconTextGap(20);
        bKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKasirActionPerformed(evt);
            }
        });

        bPenjualan.setBackground(new java.awt.Color(51, 51, 51));
        bPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        bPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-sales-30.png"))); // NOI18N
        bPenjualan.setText("Penjualan");
        bPenjualan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bPenjualan.setIconTextGap(20);

        bBarang.setBackground(new java.awt.Color(51, 51, 51));
        bBarang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bBarang.setForeground(new java.awt.Color(255, 255, 255));
        bBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-grocery-30.png"))); // NOI18N
        bBarang.setText("Barang");
        bBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bBarang.setIconTextGap(20);

        bPengaturan.setBackground(new java.awt.Color(51, 51, 51));
        bPengaturan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPengaturan.setForeground(new java.awt.Color(255, 255, 255));
        bPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-settings-30.png"))); // NOI18N
        bPengaturan.setText("Pengaturan");
        bPengaturan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bPengaturan.setIconTextGap(20);

        bUser.setBackground(new java.awt.Color(51, 51, 51));
        bUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bUser.setForeground(new java.awt.Color(255, 255, 255));
        bUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-user-30.png"))); // NOI18N
        bUser.setText("User");
        bUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bUser.setIconTextGap(20);

        bTentang.setBackground(new java.awt.Color(51, 51, 51));
        bTentang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bTentang.setForeground(new java.awt.Color(255, 255, 255));
        bTentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-about-30.png"))); // NOI18N
        bTentang.setText("Tentang");
        bTentang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bTentang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bTentang.setIconTextGap(20);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUser, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bDashboard)
                .addGap(32, 32, 32)
                .addComponent(bKasir)
                .addGap(38, 38, 38)
                .addComponent(bPenjualan)
                .addGap(40, 40, 40)
                .addComponent(bBarang)
                .addGap(41, 41, 41)
                .addComponent(bPengaturan)
                .addGap(31, 31, 31)
                .addComponent(bUser)
                .addGap(41, 41, 41)
                .addComponent(bTentang)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dinarmart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(dinarmart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home  >>");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kasir/logo/icons8-profile-50.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(411, 411, 411)
                .addComponent(jLabel4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new PanelDashboard());
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_bDashboardActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void bKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKasirActionPerformed
        // TODO add your handling code here:
        content.removeAll();
        content.add(new PanelKasir());
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_bKasirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBarang;
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bKasir;
    private javax.swing.JButton bPengaturan;
    private javax.swing.JButton bPenjualan;
    private javax.swing.JButton bTentang;
    private javax.swing.JButton bUser;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dinarmart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
